name: Publish Karpenter KWOK Helm Chart

on:
  push:
    branches:
      - main
#    paths:
#      - 'kwok/charts/**'
#      - 'tools/release/package-kwok-chart.sh'
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install yq
        uses: mikefarah/yq@v4.44.3
        with:
          cmd: version

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package chart
        id: pkg
        run: |
          bash tools/release/package-kwok-chart.sh > artefact.txt
          PKG=$(tail -n1 artefact.txt)
          echo "pkg=$PKG" >> "$GITHUB_OUTPUT"

      - name: Push to GHCR (OCI)
        run: |
          helm push "${{ steps.pkg.outputs.pkg }}" "oci://ghcr.io/${{ github.repository }}/charts"


